### ISSUE TITLE
Generator querying tricks according to difficulty is delayed

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#142]
If the user changes the difficulty slider or the checkboxes for allowed difficulties it always has the state from before the change. So the first change only takes effect after the second change.

**Comment by weberax** [comment]
I found a solution, which makes this work. But creates a different but, which lets you only change the maxdifficult level downwards and not upwards...

**Comment by weberax** [comment]
I think we should anyway do a refactor of the whole code....
We should find maybe a more clearer way for the difficultys as a state. And also not call to many refreshing functions, I think there we somehow break the "react structure", because thinks happen probably not in the right order.
And we should probably translate our combo-find problem into a pathfinding problem of a weighted graph. These we can probably better solve with already existing libaries.
