### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#161]
I talked to Gaelle and she is motivated to design a new logo for the app as soon as we have chosen our main theme colors for the app.

**Comment by hell3nacht** [comment]
hey and hello, @JulianDietzel and i played around with some logo ideas (picture below, not everything is to be taken seriously). due to the variety: feedback or preferences are highly appreciated! luzie :) 

<img width="968" alt="2024_01_06_logovarianten" src="https://github.com/bastislack/highline-freestyle/assets/132842524/9f8d95fb-7dfd-4a09-969e-450a3d38fec9">

**Comment by JulianDietzel** [comment]
To add my two cents, partially already discussed with @hell3nacht, here are the ones I like best out of the ones listed:

| Number | How much I like it (o, +, ++) | Comment |
|--------|--------|--------|
| 1 | + |  Originally I found the lines to be to thin. But they might fit the look of the app after all |
| 6 | + | Basic but works |
| 8 & 9 | ++ | Both work quite well. I have a slight preference for the thinner 8. Perhapse a less round font could look good aswell. |
| 11 & 12 | ++ | I like how "Highline" and "Freestyle" are of the same width. 12 looks a little better to me. The only think I dislike a little is how "Freestyle" is smaller than "Highline" but that's not big enough an issue to discard the idea. |
| 13 | ++ | Like it aswell, slightly better than 6 |
| 25 | o | It's ok but I like the others better | 
| 29 | ++ | I still really like the look of this one but do recognize that "Highline" is just barely legible | 
|  |  |  | 
| 21 & 22 |  | I like the usage of the initials for the small version. The only thing that bothers me is how the only slanted line is sloping downwards instead of up and down / upwards |

We were tinkering with completly different ideas where we had line drawings of an animal we used for the small and large logo (like for example a sloth, a kiwi or, after some getting used to it my current favourite, a rooster). It had a really strong energy to it. I personally would love seeing this idea explored further but myself don't have any time to spend on this.

If you don't get any feedback from the others within the next few days feel free to just go with whatever you think would be cool :+1:.

If you want to work with colors there is a wiki entry on the colors we are currently using [here](https://github.com/bastislack/highline-freestyle/wiki/Colors). The colors so far are very close to what they used to be before the rewrite so the _might_ change in the foreseeable future. I opened issue #322 to discuss what colors we want to use in the future (feel free to join / start that discussion as well).

**Comment by hell3nacht** [comment]
![image](https://github.com/bastislack/highline-freestyle/assets/132842524/f388f9ef-32ac-4df0-bf40-9caa265001ce)

(just saying)  

- 

thank you, can't promise anything. i'll post if i find time to do stuff. luzie

**Comment by bastislack** [comment]
I really like variants 12 and 15 :)
And for the small version of the logo 22 is great (just as Julian said, I think it would be cooler if the two lines of the 'F' would be tilted upwards instead of downwards).

**Comment by hell3nacht** [comment]
hey there, thank you for the feedback :) i'd like this combination as well. what do you think? luzie 

![2024_01_20_logoversion](https://github.com/bastislack/highline-freestyle/assets/132842524/7aec798e-1c28-4149-bff3-aed196d62e05)

**Comment by bastislack** [comment]
I love it! Thanks so much for creating it :)

**Comment by JulianDietzel** [comment]
Those look nice :+1:. The only nitpick I have is that the "Y" is really close to the "T". But this is a really minor issue, so feel free to not "fix" it if you don't want to.

If you are happy with the logos as well, these are two options for the next steps:
1. You export the two logos as .svg-images and post them here in this thread or to the Discord group. Then someone else can add the logos to the website / app. It's not a lot of work, I can do this if you want.
2. If you feel comfortable (or adventurous enough) working with git and the code base of the website, you can add the logos to the website / app yourself. The two places where it would need to go are
    - as the sites favicon
    - at the top of the navigation bar in the desktop view (where the "Logo" placeholder is located)

Feel free to ask questions and experiment, you currently don't have the necessary permissions to break anything. More iterations on the logo are possible as well, if you feel like this would be necessary.

Thanks for the nice logos :)

**Comment by hell3nacht** [comment]
glad u like them & thank you for the instructions. i'm trying. 
& @JulianDietzel - it 's your work as well!

**Comment by JulianDietzel** [comment]
The issue was addressed in #329 and #330, adding the logos to the project directory and subsequently adding the logo to the SideNavbar. The only thing left to do, for this issue to be fully resolved is to make the favicon work (optimally in both dark and light browsers / browser themes).

**Comment by JulianDietzel** [comment]
Finished the last thing needed, properly adding the favicon, to wrap up this issue in #333.
