### ISSUE TITLE
Updates to the tricklist are not applied if a trick is saved in the userTricks

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#194]
I changed the video link of the chrysalis but when it is ticked on the list it gets saved as a userTrick and thus is not updated.

**Comment by weberax** [comment]
I have an idea for this:
- the only atributes the user needs to change of a existing trick or combo is the lvl, frequency and other specific atributes...
- so it makes sense to only have these fields in the db and on the edit component

To simplify this process, we could also consider to simplify the whole push trick component (and the db), so that the user added tricks will be much simpler than the predefined ones. Maybe just name, lvl, and notes...

@bastislack what do you think?

**Comment by rorystephenson** [comment]
I think @weberax's solution makes sense.

Actually reading this issue made me realise it's probably time to add some testing so that we can write tests which cerufy that we handle more complex things like this correctly. I've opened a PR for it #199 .

**Comment by weberax** [comment]
_(just for the archive... no discussion needed)_

I implemented this now in 2382e36:
> Now only the explicit changes of the user are saved.
   Before we saved a copy of the original trick in the `userTricks` table, now this table only contains the explicit changed attributes.
   Also for every trick query (single or multiple) the query has to merge the `userTricks` table with the `predefinedTricks` one and by encountering duplicates, keeping the user changed value.
   This is done with the `mergeLists` function.
   
This is different to how we discussed the solution here beforehand, but should work, as long as the user never updated the fields, which we want to update as well, in this case the user won't see our update. But that might be also a good feature.

At some point we would want to probably track, and show the user, which data he modified, so he could also reset individual fields. But this we can do after maybe even considering an total refactor of the whole database.
