### ISSUE TITLE
Running dev in Chrome doesn't work

### ISSUE THREAD

**Issue by Felix-Hmpl** [bastislack/highline-freestyle#243]
When I run `npm run dev` and access app via chrome, I get the following error message:
![image](https://user-images.githubusercontent.com/60603136/225087440-23cdc79f-0eb9-408b-bb1b-35e6670a0b20.png)

It says "inkognito mode", but I am using it the regular way. 
My Chrome version: `111.0.5563.65 (Offizieller Build) (64-Bit)`

In Edge, everything works fine though

**Comment by JulianDietzel** [comment]
Not a direct solution but something closely related:
The "Unfortunatly this App does not work in incognito mode, try to disable it" message was a fix to an earlier issue where the page crashed when I tried opening it in incognito mode. Since the issue arose from Dexie (the database module) not being able to function in incognito mode, the solution was not to fix the problem (since that doesn't really seem possible) but point the user to what the problem probably is. The message is only shown if a certain type of error (`error.name === "DatabaseClosedError"`) crashes the page (implemented [here in ErrorFallback.js](https://github.com/bastislack/highline-freestyle/blob/9df194830ecdb708f5affcb8f8d2f8c2cbb2cebf/src/components/pages/ErrorFallback.js#L5)).

I have had the message come up while not in incognito mode, too, so the current check for whether or not to show the message might not be precise enough. For the moment I would suggest just changing it to something like "This problem is often caused by attempting to using the App in incognito mode. Unfortunately the App does not support this."

But what seeing the message tells us is, that the problem is most probably database related. Have you tried deleting the IndexDB in your Chrome Browser? And could you perhaps share the console log, if there is one, when the error occurs.

**Comment by weberax** [comment]
I think this is based on some database corruption (no idea when it actually happened and what caused it), like some other errors. Resetting the App like described https://github.com/bastislack/highline-freestyle/issues/224#issuecomment-1694383128 should fix it.
We can reopen the issue if it still ocurs
