### ISSUE TITLE
save scrolling position 

### ISSUE THREAD

**Issue by weberax** [bastislack/highline-freestyle#62]
When returning from the trickdetails, return to the same position you where on the tricklist. 

Or we do something like: "react Spa single page"

**Comment by bastislack** [comment]
In 61d4731 I tried to implement the scroll position remember feature as described in: https://levelup.gitconnected.com/persist-and-remember-page-scroll-position-i-e-window-scrolly-using-react-hooks-f80884211f2d
I also tried several workarounds but for me the problem is that in the return function of the useEffect hook it always displays the window.scrollY as 0 (probably the value of the page that has just been rendered), instead of getting the value just before the newly rendered page appears.
