### ISSUE TITLE
Deploy app

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#88]
We should discuss which platform we will use to deploy the app.
One option that seems good would be to use github actions and heroku.

**Comment by weberax** [comment]
Not sure if wee need something like heroku, maybe just a github page would be enough...
https://pages.github.com/

Plus an custom url.

**Comment by rorystephenson** [comment]
I'm experimenting with deploying on gh pages following along [this article]() with some changes since they are not using webpack directly to deploy.

Part of the configuration requires setting the `gh-pages` branch as the github pages source branch for this repo, do you think you can enable that @bastislack or @weberax ? According to the article it is in the settings menu:

<img width="701" alt="Screenshot 2021-11-17 at 8 05 55 PM" src="https://user-images.githubusercontent.com/3683599/142266309-02f6cb0a-632d-449c-92b8-7a722258e85a.png">

**Comment by bastislack** [comment]
Done

**Comment by bastislack** [comment]
This is the link to the site: https://bastislack.github.io/highline-freestyle/

**Comment by rorystephenson** [comment]
Took a bit of fiddling around bit it looks like it's working now.

When code is merged to `main` it gets automatically deployed to https://bastislack.github.io/highline-freestyle/ . We can change this if we want some other condition to be met before deploying (or if we want deploying to be manually triggered).

From the comments above it sounds like like we may want to buy & configure a domain name?

**Comment by bastislack** [comment]
Amazing!
A domain-name would be cool in my opinion.
highline-freestyle.com costs 12€ per year on domains.google.com.
I would for sure pay this ;)

**Comment by rorystephenson** [comment]
> Amazing! A domain-name would be cool in my opinion. highline-freestyle.com costs 12€ per year on domains.google.com. I would for sure pay this ;)

Agreed! highlinefreestyle.com is also available I think.

We can point it at the github pages URL after.

**Comment by bastislack** [comment]
So which one should we get?
highlinefreesytle.com
or 
highline-freestyle.com
@weberax 
@Felix-Hmpl

**Comment by Felix-Hmpl** [comment]
Ill vote for highline-freestyle.com

**Comment by weberax** [comment]
Same, I also prefer highline-freestyle.com

**Comment by bastislack** [comment]
I set up the new domain name, but right now it's not working. It says that it might need 24h to work so let's see if it is working tomorrow.
