### ISSUE TITLE
Why does the postTrick screen not just appear at the top as all other screens?

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#96]
If you scroll down on the trick list and then push the floating action button the post trick screen is scrolled down all the way. If you click on a trick the trick details screen is not scrolled down (this should be the default way). Why does the post trick screen behave differently?

**Comment by rorystephenson** [comment]
@bastislack I don't understand what the issue is.

I'm doing:

1. Scroll down trick list.
2. Click new trick button. (at this point I'm at the start of the page as expected).
3. Hit back button. (now I'm back at the start of the list, it would be nice to go back to the previous scroll but I'm not sure that's what this is about).

**Comment by bastislack** [comment]
Sorry for the confusion!
I fixed the issue with the scroll to top in 3fd676.
So now it is working but only because I wrapped the PostTrick component in the new ScrollToTop component.
I am still wondering why we need to use the ScrollToTop component here and nowhere else?
